spring:
  profiles:
    active: dev #开发环境配置
  #热部署
  devtools:
    restart:
      enabled: true #设置开启热部署
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

    #使用Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    # 获取连接等待超时的时间
    maxWait: 60000
    minIdle: 1
    # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #thymeleaf配置
  thymeleaf:
    cache: false # 关闭页面缓存
    encoding: UTF-8 # 模板编码
    prefix: classpath:/templates/  # 页面映射路径
    suffix: .html # 试图后的后缀
    mode: HTML5 # 模板模式
  #分页插件

mybatis:
  type-aliases-package: com.lzp.blog.dao #扫描mapper文件
  mapper-locations: classpath*:/mapper/*.xml #读取xml文件
  configuration:
   map-underscore-to-camel-case: true  #开启驼峰转换
logging:
  config: classpath:log4j2.xml #加载配置文件
  level:
    com.lzp.blog.dao: DEBUG #sql打印
pagehelper:
  helper-dialect: mysql
  params: count = countsql
  reasonable: false #当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  support-methods-arguments: true
